[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2C4A63"
backgroundColor = "#F5F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B2A38"
font = "sans serif"
